version: "3"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"

  db:
    image: mariadb:10.5
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro



