version: "3"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"

  db:
    image: mariadb:10.5
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  dash:
    build: ./dash
    ports:
      - "8050:8050"
    depends_on:
      - app
    environment:
      FLASK_HOST: app
      FLASK_PORT: 5000



